// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmDMjaV_nooiI3N4ebatRUAPVkxLgacDA',
    appId: '1:40233588836:web:0b0b382806d77916ac6771',
    messagingSenderId: '40233588836',
    projectId: 'dentex-clean',
    authDomain: 'dentex-clean.firebaseapp.com',
    storageBucket: 'dentex-clean.firebasestorage.app',
    measurementId: 'G-KHQ88F55Z1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASx7Siu9CBckt0cTvqEFRGK4oThu8mQjc',
    appId: '1:40233588836:android:7bab36c289361deeac6771',
    messagingSenderId: '40233588836',
    projectId: 'dentex-clean',
    storageBucket: 'dentex-clean.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhdgA3QdYEvNh2LyntLVXba1l7IEiLIYk',
    appId: '1:40233588836:ios:3fbf476fb04b2930ac6771',
    messagingSenderId: '40233588836',
    projectId: 'dentex-clean',
    storageBucket: 'dentex-clean.firebasestorage.app',
    iosBundleId: 'com.example.dentexClean',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhdgA3QdYEvNh2LyntLVXba1l7IEiLIYk',
    appId: '1:40233588836:ios:3fbf476fb04b2930ac6771',
    messagingSenderId: '40233588836',
    projectId: 'dentex-clean',
    storageBucket: 'dentex-clean.firebasestorage.app',
    iosBundleId: 'com.example.dentexClean',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmDMjaV_nooiI3N4ebatRUAPVkxLgacDA',
    appId: '1:40233588836:web:5ef21b98776ef36aac6771',
    messagingSenderId: '40233588836',
    projectId: 'dentex-clean',
    authDomain: 'dentex-clean.firebaseapp.com',
    storageBucket: 'dentex-clean.firebasestorage.app',
    measurementId: 'G-9S4Y10WLYF',
  );
}
